name: Check ImmortalWrt Version

on:
  workflow_dispatch:

jobs:
  check-version:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show REAL VERSION
        run: |
          echo "===== Version Info ====="
          cat include/version
          echo "===== Kernel Config ====="
          cat target/linux/filogic/config-5.15 | grep "CONFIG_VERSION"
